### ISSUE TITLE
external RAM

### ISSUE THREAD

**Issue by AndreasDa** [sifive/freedom-e-sdk#101]
Is there already a memory controller for the external ddr3 ram on the digilent arty board shipped with the freedom-e-sdk?
If so, how can I set it up so that I can store data in this ram?
As always, thanks in advance.

**Comment by dbarbi1** [comment]
The Core IP Evaluation images we provide, which target the Arty board, do not currently support the on-board DDR3 memory. We are interested in adding this ability in the future, but it is not work we have scheduled yet.
