### ISSUE TITLE
Import Apache-licensed Coremark

### ISSUE THREAD

**Issue by arunthomas** [sifive/freedom-e-sdk#105]
Coremark is Apache-licensed as of a few months ago: https://github.com/eembc/coremark

Would you be willing to import the Apache-licensed Coremark sources into the SDK?

**Comment by brucehoult** [comment]
That sounds like a good idea ... we already have the framework for running Coremark in software/coremark @palmer-dabbelt

**Comment by nategraff-sifive** [comment]
Done!

**Comment by arunthomas** [comment]
Thanks, @nategraff-sifive!
