### ISSUE TITLE
Cannot build projects including "platform.h" file

### ISSUE THREAD

**Issue by kammce** [sifive/freedom-e-sdk#134]
Attempting to perform: `make BSP=mee PROGRAM=led_fade BOARD=sifive-hifive1 software`

Results in the following:
```
led_fade.c:7:10: fatal error: platform.h: No such file or directory
 #include "platform.h"
          ^~~~~~~~~~~~
compilation terminated.
```

**Comment by jim-wilson** [comment]
freedom-e-sdk is in transition from the old way of doing things to the new way (libmee), and is likely to be broken for a while.  I would suggest checking out a copy before the transition started in mid December.  The last commit before the transition was in September, commit id baeeb8fd497a99b3c141d7494309ec2e64f19bdf.  If you checkout the commit in an active tree, don't forget to rerun git submodules update --init --recursive, and you will have to rm -rf some dirs and submodules that changed between the two versions.  git status will show you what needs to be removed.

**Comment by kammce** [comment]
Awesome! Thank you for the advice.
