### ISSUE TITLE
[sifive-hifive1-revb] Missing DeviceTree label LD0 for RGB led

### ISSUE THREAD

**Issue by jumapico** [sifive/freedom-e-sdk#243]
Hi.

After compilation and upload of [sifive-welcome example](https://github.com/sifive/sifive-welcome/blob/master/sifive-welcome.c) the serial console gives the message: `At least one of LEDs is null.`

According [metal documentation](https://sifive.github.io/freedom-metal-docs/apiref/led.html) is needed that the led had a label in the DeviceTree, what's missing.

Regards,
JMPC

**Comment by bsousi5** [comment]
Thanks for reporting this. This has been fix in the development-19.05 branch and will be available in the coming release

- Bunnaroath
