### ISSUE TITLE
sifive-welcome does not work on HiFive1 RevB

### ISSUE THREAD

**Issue by brucehoult** [sifive/freedom-e-sdk#247]
Prints "At least one of LEDs is null" and no LED fade happens.

The preloaded version works.

**Comment by nategraff-sifive** [comment]
This is fixed in development-19.05

**Comment by brucehoult** [comment]
When is that expected to be released? 31st?

In the meantime, do you think it's better to point HiFive1 Rev B owners to that branch, or can a fix be comitted to master before the full release?

**Comment by nategraff-sifive** [comment]
This is now fixed.
