### ISSUE TITLE
dhrystone does not work on HiFive1 RevB

### ISSUE THREAD

**Issue by brucehoult** [sifive/freedom-e-sdk#249]
Unlike in the old v1_0 code there is no longer a hack to replace scanf() with a version that returns a hard-coded value.

    printf ("Please give the number of runs through the benchmark: ");
    {
      int n;
      scanf ("%d", &n);
      Number_Of_Runs = DHRY_ITERS;
    }

The scanf() just hangs. Or at least I can't find anything I can type as input that makes it continue. I tried a number followed by various of " ", return, ^J, ^M.

The return value isn't used anyway. Commenting out the scanf() makes it work, with a printed result of 333 dhrystones per second with the default 2000 iters, 335 if I increase it a lot e.g. 100000.

**Comment by nategraff-sifive** [comment]
This is working for me now in v201905, though the default iterations in settings.mk is 20,000,000, which is a bit excessive. Probably a good idea to bump that down.
