### ISSUE TITLE
Fail to download program on Arty E76/S76 after flash with *.bit

### ISSUE THREAD

**Issue by virtualboots** [sifive/freedom-e-sdk#308]
For CPU cores except E76/S76, I can download program on Arty cores after flashing the board with the *.bit file.

However, the program download will show timeout message for E76/S76.

This can be workaround if I flash the board with *.mcs file through FreedomStudio.

**Comment by nategraff-sifive** [comment]
This sounds more like it might be a bitstream generation problem than a Freedom E SDK problem.

Also, I'd recommend against filing GitHub issues for stuff like this. Let's take this discussion internal.
