### ISSUE TITLE
How to upload standalone projects

### ISSUE THREAD

**Issue by benmezger** [sifive/freedom-e-sdk#313]
I've created a standalone project out of the `example-user-mode`, but I wonder how can I upload. By doing `make metal_install` gives me:

```
/Library/Developer/CommandLineTools/usr/bin/make -C freedom-metal install
make[1]: *** No rule to make target `install'.  Stop.
make: *** [metal_install] Error 2
```

since `src/Makefile` has no `install` option. Any help would be appreciated. Thanks

**Comment by nategraff-sifive** [comment]
Hi @benmezger,

You should be able to upload from the standalone project simply by running `make upload`.
