### ISSUE TITLE
Metal interrupt: Async vs sync interrupt

### ISSUE THREAD

**Issue by benmezger** [sifive/freedom-e-sdk#352]
When handling CPU interrupts and timer interrupts, how can I know whether the interrupt was an async interrupt or a sync interrupt? Does Freedom-metal has a function to handle this? Because at the moment, I am receiving interrupt codes such as 5, but I am not sure if its a supervisor interrupt or a load access fault. 

Thanks in advanced.

**Comment by nategraff-sifive** [comment]
Hi Ben,

In Freedom E SDK and Freedom Metal, we refer to synchronous interrupts as "exceptions" and are registered to exception handlers using the [Metal CPU API](https://sifive.github.io/freedom-metal-docs/apiref/cpu.html), whereas asynchronous interrupts are referred to as "interrupts" and are registered to interrupt handlers using the [Metal Interrupt API](https://sifive.github.io/freedom-metal-docs/apiref/interrupt.html).

Therefore, the only way to register a handler for the load access fault exception is with the [`metal_cpu_exception_register()`](https://sifive.github.io/freedom-metal-docs/apiref/cpu.html#_CPPv328metal_cpu_exception_registerP9metal_cpui25metal_exception_handler_t) function, and conversely the supervisor timer interrupt handler can only be registered with [`metal_interrupt_register_handler()`](https://sifive.github.io/freedom-metal-docs/apiref/interrupt.html#_CPPv332metal_interrupt_register_handlerP15metal_interrupti25metal_interrupt_handler_tPv).

Hope this helps,
Nate
