### ISSUE TITLE
entry.S saves too many registers

### ISSUE THREAD

**Issue by tdaede** [sifive/freedom-e-sdk#39]
As far as I can tell, based on the riscv C calling convention, many of the registered saved in handled_trap don't actually need to be saved when calling a C interrupt handler, such as x8, x9, x18-27.

**Comment by aswaterman** [comment]
That is true.  This code is borrowed from a more sophisticated kernel entry point that performs context switches and manipulates the user context for other reasons.  In those cases, the simplest approach is to spill the whole context.

Feel free to optimize it for your purposes.

Of course, lower-latency interrupt handlers would only spill the registers they actually intended to use, which could be accomplished with an alternate C ABI that treats nearly all registers as callee-saved.  This would typically save quite a bit more instructions than the simple approach.
