### ISSUE TITLE
No LICENCE file

### ISSUE THREAD

**Issue by frantony** [sifive/freedom-e-sdk#4]
Some files (e.g. [software/shared/uart.h](https://github.com/sifive/freedom-e-sdk/blob/master/software/shared/uart.h)) mention a LICENSE file:
```
// See LICENSE for license details.
```
However the repo does not contain any LICENSE file!

**Comment by mwachs5** [comment]
Good point! It should be Apache 2.0 licensed. Will get that up there shortly.

Note that the subrepos already have their own license files.

**Comment by mwachs5** [comment]
LICENSE file added.
