### ISSUE TITLE
BSP for COREIP-E21 is needed for v201908-branch.

### ISSUE THREAD

**Issue by Aegon7** [sifive/freedom-e-sdk#453]
The latest branch (v201908) has many changes in the freedom-metal library (compared to 201903 branch). 
We need a new BSP to support that changes for E21 core. 
It'll be helpful if you can port the E21 core BSP from v201903 to v201908.

**Comment by nategraff-sifive** [comment]
Hi @Aegon7, it sounds like you're a customer of SiFive Core Designer. Can you file a support request by emailing support@sifive.com? We're not set up to handle support requests through GitHub issues. Thanks!
