### ISSUE TITLE
Freedom E300 Vivado 2017.3  implementation problem.

### ISSUE THREAD

**Issue by Tonmoyibnearif** [sifive/freedom-e-sdk#516]
[Place 30-574] Poor placement for routing between an IO pin and BUFG. If this sub optimal condition is acceptable for this design, you may use the CLOCK_DEDICATED_ROUTE constraint in the .xdc file to demote this message to a WARNING. However, the use of this override is highly discouraged. These examples can be used directly in the .xdc file to override this clock rule.
	< set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets E300/IOBUF_6/O] >

	E300/IOBUF_6/IBUF (IBUF.O) is locked to IOB_X0Y16
	 and E300/IOBUF_6_O_BUFG_inst (BUFG.I) is provisionally placed by clockplacer on BUFGCTRL_X0Y0

**Comment by knightsifive** [comment]
Your question concerns a Vivado error message, discussed further on the Xilinx website here: https://www.xilinx.com/support/answers/64452.html

This repo is for Freedom-E-SDK --- a "software development kit" --- and is not the appropriate place to get support for errors from Xilinx tools.
