### ISSUE TITLE
File I/O on QEMU ?

### ISSUE THREAD

**Issue by balaji-ch** [sifive/freedom-e-sdk#554]
Hi,

I tried to tweak the hello world application and used FILE I/O as follows

```
printf("Testing ---- Before ! \n");

FILE *fp;
fp = fopen("test_rv.txt", "w+");

if(fp==NULL)
{
printf("%d\n", errno);
printf("Error in opening the file. err = %s\n", strerror(errno));
}

printf("Testing ---- After ! \n");
```

**and the output is** 
```

Hello, World!
Testing ---- Before !
88
Error in opening the file. err = Function not implemented
Testing ---- After !

```

**Is there any way that I can use FILE I/O ?**

The build instructions that I followed are from here.
https://twilco.github.io/riscv-from-scratch/2019/03/10/riscv-from-scratch-1.html

**Comment by nategraff-sifive** [comment]
Hi @balaji-ch,

This project is for writing embedded code, where there's no operating system to provide a file abstraction. If you're interested in writing some code on RISC-V that provides the environment you're familiar with, you'd be better off running a Linux distro like Debian in QEMU: https://wiki.debian.org/RISC-V
