### ISSUE TITLE
Basic SoC with E24 rtl Core

### ISSUE THREAD

**Issue by 1610Pablo** [sifive/freedom-e-sdk#561]
I want to make a basi SoC with the E24 core. I'm using block design with Vivado and I would like to know
if it's possible to replace the BonFire Core I have now with the rtl module of the E24.

This is the basic SoC I want to develope, replacing the bonfire axi top with the E24.
![bonfire](https://user-images.githubusercontent.com/72968758/96703930-bc960280-1393-11eb-8bfb-5273bcd3a975.PNG)

Thanks

**Comment by nategraff-sifive** [comment]
This is unrelated to freedom-e-sdk, a SiFive Customer Experience engineer should be following up with you.
