### ISSUE TITLE
RISC-V toolchain - can't target rv32i & ilp32?

### ISSUE THREAD

**Issue by Slava0135** [sifive/freedom-e-sdk#594]
![image](https://user-images.githubusercontent.com/40753025/115118041-188bbd80-9faa-11eb-872a-9070046aaf7c.png)

**Comment by nick-knight** [comment]
The RISC-V GNU toolchain certainly supports RV32I/ILP32. But the toolchain binaries that SiFive bundles with its "Freedom Tools" distribution (what you're using?) do not include "multilib" support for all possible ISA/ABI combinations. Instead, SiFive focuses on the combinations corresponding to its products, plus maybe a few others. If you have a use-case beyond the provided multilibs, you'll have to build your own toolchain. Head over to riscv/riscv-gnu-toolchain and learn how!

**Comment by Slava0135** [comment]
I use version 10.2.0 of the pre-built toolchain.
Thanks for the response.
