### ISSUE TITLE
Not  "ARM-USB-TINY-H" debuger,use sdk commands uploading programs to Arty 7 encountered some problems

### ISSUE THREAD

**Issue by Pengnian** [sifive/freedom-e-sdk#68]
Hi ,all

I'm  not use ARM-USB-TINY-H debuger, my jtag cable is "Xilinx platform cable USB". So,when I want to uploading program to my board(ARTY 7) by freedom-e-sdk commands, encountered some troubles. How to show the result of  executing program in my board .
![0701_3](https://user-images.githubusercontent.com/26727603/27758707-50058f44-5e4e-11e7-90c0-ad57d7fb3a6f.jpg)

![screen](https://user-images.githubusercontent.com/26727603/27758698-18b1d840-5e4e-11e7-823f-28c0adf2a603.png)

**Comment by timsifive** [comment]
You would have to change the config file to whatever configuration is required to have OpenOCD use your Xilinx Platform Cable USB. Googling suggests some people have made this work, but all the references are old and some mention special kernel modules.

You could try to figure that out, but I suspect it's more efficient to just by an ARM-USB-TINY-H.

Given the OpenOCD error messages, I do not believe the message that says the upload was successful.

**Comment by mwachs5** [comment]
Yes, the "successful" error message is misleading. We need to fix the Makefile target which prints that.

**Comment by Pengnian** [comment]
@timsifive Hi,Tim

Thanks your advice, I have brought the "ARM-USB-TINY-H" debugger, but situation not any change!
![111](https://user-images.githubusercontent.com/26727603/28014278-a7ec1fd2-659e-11e7-9a2d-9f405ab912c5.png)

**Comment by Pengnian** [comment]
@timsifive Thanks your advice, I have brought the "ARM-USB-TINY-H" debugger, but situation not any change! just use command of `make upload PROGRAM=hello BOARD=freedom-e300-arty` on freedom-e-sdk.


![debugger](https://user-images.githubusercontent.com/26727603/28014473-55550de6-659f-11e7-8119-34d3b2dd3740.png)

**Comment by timsifive** [comment]
This is actually a big improvement. Previously OpenOCD was not able to talk
to your JTAG adapter. Now it is able to talk to the adapter, but when it
tries to talk to the RISC-V core something is going wrong.
This could be as simple as the board not being powered on or not programmed
with the right FPGA image, but I think the most likely problem is the
wiring between the Olimex adapter and the Arty board.

Tim

**Comment by Pengnian** [comment]
@timsifive  Hi,Tim
At first ,thank your advice! The LED of debugger is light when connection between board and computer .
But when I use command "make upload PROGRAM=hello BOARD=freedom-e300-arty",the led not bright ! But every time the errors maybe difference!

![jtag](https://user-images.githubusercontent.com/26727603/28059899-3d2b06e4-6658-11e7-8322-4344698ef07e.png)

**Comment by timsifive** [comment]
The Makefile right now is making things more confusing. It looks like
OpenOCD starts, but then gdb can’t connect for some reason. I’d try running
things manual. So start OpenOCD in one shell (openocd -f
bsp/env/freedom-e300-arty/openocd.cfg), and then run gdb in another shell (
gdb, then target remote localhost:3333).

This may just be a timing issue where the Makefile starts gdb before
OpenOCD has fully started up.

Tim
​
