### ISSUE TITLE
Not able to download all sub-folders data in windows through ZIP file of freedom-e-sdk

### ISSUE THREAD

**Issue by thotaraghava** [sifive/freedom-e-sdk#85]
Hi Everybody,

      I wanted to install freedom-s-sdk to work on PULPino simulations.
      I have downloaded ZIP file from github and could see sub folders data missing.
      Can you tell me how to download entire database.

     Your help is highly appreciated.

Thanks,

**Comment by ilg-ul** [comment]
I guess those subfolders are git submodules.

try to clone the repository and be sure you recurse on submodules.

**Comment by thotaraghava** [comment]
Yes, they are git sub modules.
Please tell me how to recurse on submodules while downloading onto windows.
Thanks for responding.

**Comment by thotaraghava** [comment]
How to do this command while downloading ZIP file in windows.

git clone --recursive <URL-OF-REPOSITORY>

**Comment by ilg-ul** [comment]
ignore the ZIPs, you need to clone the repository.

**Comment by thotaraghava** [comment]
Should I download GitHub Desktop for this.

**Comment by ilg-ul** [comment]
nope, git is enough.

**Comment by thotaraghava** [comment]
![git](https://user-images.githubusercontent.com/35065570/34607990-26b877be-f23c-11e7-8334-e519134b3015.png)
 Which option I need to take. Open in Desktop is asking to download GitHub Desktop, the other option left is ZIP file.

**Comment by thotaraghava** [comment]
Yes, GitHub Desktop looks working. I have installed and trying to clone, process is going on.
Thanks a lot for your patience ilg-ul.

**Comment by ilg-ul** [comment]
BTW, after you manage to clone the repository, all you can do is examine the files.

if you want to build the samples, you also need the toolchain, a functional make and possibly more.

**Comment by thotaraghava** [comment]
ok, sure.

**Comment by thotaraghava** [comment]
HI,
 In the path /freedom-e-sdk/riscv-gnu-toolchain/riscv-binutils-gdb/, I dont see any configure file both in web page as well as in cloned database.
But while running make tools [BOARD=freedom-e300-hifive1], I am seeing below error. 

freedom-e-sdk/riscv-gnu-toolchain/riscv-binutils-gdb/configure: No such file or directory.

Please help.

**Comment by ilg-ul** [comment]
the path of building the toolchain from sources requires a Linux system and some good Linux knowledge.

perhaps you should try to use the already made binaries.

alternatively you can use Eclipse, it is easier to use for first time users. in the latest version of GNU MCU Eclipse you have a SiFive project template that generates ready to run HiFive1 blinky projects.

**Comment by thotaraghava** [comment]
Already made binaries means, the database on which somebody did already right

**Comment by ilg-ul** [comment]
it means ready to run executables, not source code programs that need to be compiled, like you are trying to do.

**Comment by thotaraghava** [comment]
ok
